module.exports = {
    "@body-background": "#F0F2F5;",
    "@border-radius-base": "4px;",
    "@primary-color": "#0c85ee;",
    "@error-color": "#F12525;",
    "@highlight-color": "#F12525;",
    "@text-color": "#454e61;",
    "@border-color-base": "#b7becb;",
    "@disabled-color": "#b7becb;",
    "@disabled-bg": "#f1f3f7;",
    "@line-height-base": "1.5;",
    "@font-size-base": "12px;",
    "@font-size-lg": "@font-size-base + 2px;",
    "@border-color-split": "#dfe5ed;",
    "@heading-color": "#2a2e3c;",
    "@layout-header-background": "#2a2e3c;",
    "@layout-trigger-background": "#2a2e3c;",
    "@menu-dark-submenu-bg": "#2a2e3c;",
    "@font-family": "\"ZenOpenSansSelf, Microsoft Yahei, PingFangSC-Regular,PingFang SC\";",
    "@pagination-font-family": "'ZenOpenSansSelf, Microsoft Yahei, PingFangSC-Regular,PingFang SC';",
    "@shadow-color": "hsla(227, 18%, 20%, 0.12);",
    "border-color-base": "#b7becb;",
    "border-width-base": "1px;",
    "border-style-base": "solid;",
    "@btn-font-weight": "normal;",
    "@btn-danger-color": "#ffffff;",
    "@btn-danger-border": "transparent;",
    "@btn-danger-bg": "#F12525;",
    "@btn-disable-border": "#d7dce8;",
    "@btn-padding-base": "0  4px * 4px;",
    "@btn-padding-sm": "0  4px * 2px;",
    "@btn-font-size-lg": "16px;",
    "@btn-font-size-sm": "12px;",
    "@btn-height-base": "32px;",
    "@btn-height-lg": "46px;",
    "@btn-height-sm": "24px;",
    "@input-height-base": "32px;",
    "@input-height-lg": "46px;",
    "@input-height-sm": "24px;",
    "@input-padding-horizontal": "12px;",
    "@input-padding-horizontal-sm": "8px;",
    "@input-padding-horizontal-lg": "16px;",
    "@input-padding-vertical-base": "5px;",
    "@input-padding-vertical-sm": "3px;",
    "@input-padding-vertical-lg": "12px;",
    "@input-addon-bg": "#f1f3f7;",
    "@outline-width": "0;",
    "@checkbox-size": "12px;",
    "@radio-size": "12px;",
    "@radio-button-hover-color": "#004ba1;",
    "@form-item-margin-bottom": "12px;",
    "@tag-default-bg": "#eef1f4;",
    "@tag-font-size": "14px;",
    "@table-header-bg": "#f1f3f7;",
    "@table-header-color": "#454e61;",
    "@menu-collapsed-width": "56px;"
}